@startuml

class TrimSqlNode.FilteredDynamicContext extends DynamicContext

note top of DynamicContext
    使用ContextMap包裹入参参数，并且存储了<bind>标签绑定的参数
    使用StringJoiner来拼接jdbc标准的sql
end note

note top of TrimSqlNode.FilteredDynamicContext
    使用StringBuffer来拼接jdbc标准的sql，并且处理前缀和后缀
    最终将拼接好的sql语句添加到StringJoiner对象中（为与父类DynamicContext的api保持一致）
end note

class ForEachSqlNode.PrefixedContext extends DynamicContext

note top of ForEachSqlNode.PrefixedContext
    处理foreach分隔符前缀
end note

class ForEachSqlNode.FilteredDynamicContext extends DynamicContext

note top of ForEachSqlNode.FilteredDynamicContext
    平铺foreach循环
    每次循环中的临时变量使用内在定义的变量名（各不相同，因此可以平铺）来引用，并且用来替换sql中的变量名（相同的）
end note

@enduml